package com.google.android.gms.internal;

import android.content.Context;
import android.content.SharedPreferences;
import com.google.android.gms.ads.internal.zzbs;
import com.p005rd.pageindicatorview.BuildConfig;
import com.safonov.speedreading.training.fragment.truecolors.training.presenter.TrueColorsPresenter;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;
import org.solovyev.android.checkout.ResponseCodes;

@zzzb
public final class zzmq {
    private static zzmg<String> zzbfx = zzmg.zza(0, "gads:sdk_core_experiment_id");
    public static final zzmg<String> zzbfy = zzmg.zza(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    private static zzmg<Boolean> zzbfz = zzmg.zza(0, "gads:request_builder:singleton_webview", (Boolean) false);
    private static zzmg<String> zzbga = zzmg.zza(0, "gads:request_builder:singleton_webview_experiment_id");
    private static zzmg<Boolean> zzbgb = zzmg.zza(0, "gads:sdk_use_dynamic_module", (Boolean) true);
    private static zzmg<String> zzbgc = zzmg.zza(0, "gads:sdk_use_dynamic_module_experiment_id");
    public static final zzmg<Boolean> zzbgd = zzmg.zza(0, "gads:sdk_crash_report_enabled", (Boolean) false);
    private static zzmg<Boolean> zzbge = zzmg.zza(0, "gads:sdk_crash_report_full_stacktrace", (Boolean) false);
    private static zzmg<String> zzbgf = zzmg.zza(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final zzmg<Boolean> zzbgg = zzmg.zza(0, "gads:block_autoclicks", (Boolean) false);
    private static zzmg<String> zzbgh = zzmg.zza(0, "gads:block_autoclicks_experiment_id");
    private static zzmg<String> zzbgi = zzmg.zza(0, "gads:spam_app_context:experiment_id");
    public static final zzmg<Boolean> zzbgj = zzmg.zza(1, "gads:spam_app_context:enabled", (Boolean) false);
    private static zzmg<Integer> zzbgk = zzmg.zza(1, "gads:http_url_connection_factory:timeout_millis", (int) ResponseCodes.SERVICE_NOT_CONNECTED);
    public static final zzmg<String> zzbgl = zzmg.zza(1, "gads:video_exo_player:version", "1");
    public static final zzmg<Integer> zzbgm = zzmg.zza(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final zzmg<Integer> zzbgn = zzmg.zza(1, "gads:video_exo_player:read_timeout", 8000);
    public static final zzmg<Integer> zzbgo = zzmg.zza(1, "gads:video_exo_player:loading_check_interval", 1048576);
    private static zzmg<String> zzbgp = zzmg.zza(0, "gads:video_stream_cache:experiment_id");
    public static final zzmg<Integer> zzbgq = zzmg.zza(1, "gads:video_stream_cache:limit_count", 5);
    public static final zzmg<Integer> zzbgr = zzmg.zza(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final zzmg<Integer> zzbgs = zzmg.zza(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final zzmg<Long> zzbgt = zzmg.zza(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final zzmg<Long> zzbgu = zzmg.zza(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final zzmg<Integer> zzbgv = zzmg.zza(1, "gads:video_stream_cache:connect_timeout_millis", (int) ResponseCodes.SERVICE_NOT_CONNECTED);
    public static final zzmg<Boolean> zzbgw = zzmg.zza(0, "gads:video:metric_reporting_enabled", (Boolean) false);
    public static final zzmg<String> zzbgx = zzmg.zza(1, "gads:video:metric_frame_hash_times", "");
    public static final zzmg<Long> zzbgy = zzmg.zza(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final zzmg<Boolean> zzbgz = zzmg.zza(1, "gads:video:force_watermark", (Boolean) false);
    public static final zzmg<Long> zzbha = zzmg.zza(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final zzmg<Boolean> zzbhb = zzmg.zza(1, "gads:video:spinner:enabled", (Boolean) false);
    public static final zzmg<Integer> zzbhc = zzmg.zza(1, "gads:video:spinner:scale", 4);
    public static final zzmg<Long> zzbhd = zzmg.zza(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final zzmg<Boolean> zzbhe = zzmg.zza(1, "gads:video:aggressive_media_codec_release", (Boolean) false);
    public static final zzmg<Boolean> zzbhf = zzmg.zza(1, "gads:memory_bundle:debug_info", (Boolean) false);
    public static final zzmg<Boolean> zzbhg = zzmg.zza(1, "gads:memory_bundle:runtime_info", (Boolean) true);
    public static final zzmg<String> zzbhh = zzmg.zza(1, "gads:video:codec_query_mime_types", "");
    public static final zzmg<Integer> zzbhi = zzmg.zza(1, "gads:video:codec_query_minimum_version", 16);
    private static zzmg<Boolean> zzbhj = zzmg.zza(0, "gads:ad_id_app_context:enabled", (Boolean) false);
    private static zzmg<Float> zzbhk = zzmg.zza(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
    private static zzmg<String> zzbhl = zzmg.zza(0, "gads:ad_id_app_context:experiment_id");
    private static zzmg<String> zzbhm = zzmg.zza(0, "gads:ad_id_use_shared_preference:experiment_id");
    private static zzmg<Boolean> zzbhn = zzmg.zza(0, "gads:ad_id_use_shared_preference:enabled", (Boolean) false);
    private static zzmg<Float> zzbho = zzmg.zza(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0f);
    private static zzmg<Boolean> zzbhp = zzmg.zza(0, "gads:ad_id_use_persistent_service:enabled", (Boolean) false);
    private static zzmg<String> zzbhq = zzmg.zzb(0, "gads:looper_for_gms_client:experiment_id");
    public static final zzmg<Boolean> zzbhr = zzmg.zza(0, "gads:looper_for_gms_client:enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbhs = zzmg.zza(0, "gads:sw_ad_request_service:enabled", (Boolean) true);
    private static zzmg<Boolean> zzbht = zzmg.zza(0, "gads:sw_dynamite:enabled", (Boolean) true);
    public static final zzmg<String> zzbhu = zzmg.zza(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final zzmg<String> zzbhv = zzmg.zza(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final zzmg<String> zzbhw = zzmg.zza(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final zzmg<Boolean> zzbhx = zzmg.zza(0, "gads:enabled_sdk_csi", (Boolean) false);
    public static final zzmg<String> zzbhy = zzmg.zza(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final zzmg<Boolean> zzbhz = zzmg.zza(0, "gads:sdk_csi_write_to_file", (Boolean) false);
    public static final zzmg<Boolean> zzbia = zzmg.zza(0, "gads:enable_content_fetching", (Boolean) true);
    public static final zzmg<Integer> zzbib = zzmg.zza(0, "gads:content_length_weight", 1);
    public static final zzmg<Integer> zzbic = zzmg.zza(0, "gads:content_age_weight", 1);
    public static final zzmg<Integer> zzbid = zzmg.zza(0, "gads:min_content_len", 11);
    public static final zzmg<Integer> zzbie = zzmg.zza(0, "gads:fingerprint_number", 10);
    public static final zzmg<Integer> zzbif = zzmg.zza(0, "gads:sleep_sec", 10);
    public static final zzmg<Boolean> zzbig = zzmg.zza(1, "gads:enable_content_url_hash", (Boolean) true);
    public static final zzmg<Integer> zzbih = zzmg.zza(1, "gads:content_vertical_fingerprint_number", 100);
    public static final zzmg<Boolean> zzbii = zzmg.zza(1, "gads:enable_content_vertical_hash", (Boolean) true);
    public static final zzmg<Integer> zzbij = zzmg.zza(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final zzmg<Integer> zzbik = zzmg.zza(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final zzmg<String> zzbil = zzmg.zza(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final zzmg<String> zzbim = zzmg.zza(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final zzmg<Boolean> zzbin = zzmg.zza(0, "gad:app_index_enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbio = zzmg.zza(1, "gads:content_fetch_disable_get_title_from_webview", (Boolean) false);
    public static final zzmg<Boolean> zzbip = zzmg.zza(0, "gads:app_index:without_content_info_present:enabled", (Boolean) true);
    public static final zzmg<Long> zzbiq = zzmg.zza(0, "gads:app_index:timeout_ms", 1000);
    private static zzmg<String> zzbir = zzmg.zza(0, "gads:app_index:experiment_id");
    private static zzmg<String> zzbis = zzmg.zza(0, "gads:kitkat_interstitial_workaround:experiment_id");
    public static final zzmg<Boolean> zzbit = zzmg.zza(0, "gads:kitkat_interstitial_workaround:enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbiu = zzmg.zza(0, "gads:interstitial_follow_url", (Boolean) true);
    public static final zzmg<Boolean> zzbiv = zzmg.zza(0, "gads:interstitial_follow_url:register_click", (Boolean) true);
    private static zzmg<String> zzbiw = zzmg.zza(0, "gads:interstitial_follow_url:experiment_id");
    private static zzmg<Boolean> zzbix = zzmg.zza(0, "gads:analytics_enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbiy = zzmg.zza(0, "gads:ad_key_enabled", (Boolean) false);
    public static final zzmg<Boolean> zzbiz = zzmg.zza(1, "gads:sai:enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbja = zzmg.zza(1, "gads:sai:banner_ad_enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbjb = zzmg.zza(1, "gads:sai:native_ad_enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbjc = zzmg.zza(1, "gads:sai:interstitial_ad_enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbjd = zzmg.zza(1, "gads:sai:rewardedvideo_ad_enabled", (Boolean) true);
    public static final zzmg<String> zzbje = zzmg.zza(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final zzmg<String> zzbjf = zzmg.zza(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    public static final zzmg<Boolean> zzbjg = zzmg.zza(1, "gads:sai:click_gmsg_enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbjh = zzmg.zza(1, "gads:sai:using_macro:enabled", (Boolean) false);
    public static final zzmg<String> zzbji = zzmg.zza(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final zzmg<Long> zzbjj = zzmg.zza(1, "gads:sai:timeout_ms", -1);
    public static final zzmg<Integer> zzbjk = zzmg.zza(1, "gads:sai:scion_thread_pool_size", 5);
    private static zzmg<Integer> zzbjl = zzmg.zza(0, "gads:webview_cache_version", 0);
    public static final zzmg<Boolean> zzbjm = zzmg.zza(1, "gads:webview:ignore_over_scroll", (Boolean) true);
    private static zzmg<String> zzbjn = zzmg.zzb(0, "gads:pan:experiment_id");
    public static final zzmg<Boolean> zzbjo = zzmg.zza(1, "gads:rewarded:adapter_initialization_enabled", (Boolean) false);
    public static final zzmg<Long> zzbjp = zzmg.zza(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final zzmg<Boolean> zzbjq = zzmg.zza(1, "gads:app_activity_tracker:enabled", (Boolean) true);
    public static final zzmg<Long> zzbjr = zzmg.zza(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final zzmg<Long> zzbjs = zzmg.zza(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final zzmg<Boolean> zzbjt = zzmg.zza(1, "gads:adid_values_in_adrequest:enabled", (Boolean) false);
    public static final zzmg<Long> zzbju = zzmg.zza(1, "gads:adid_values_in_adrequest:timeout", 2000);
    public static final zzmg<Boolean> zzbjv = zzmg.zza(1, "gads:disable_adid_values_in_ms", (Boolean) false);
    public static final zzmg<Boolean> zzbjw = zzmg.zza(1, "gads:enable_ad_loader_manager", (Boolean) true);
    private static zzmg<Boolean> zzbjx = zzmg.zza(0, "gads:ad_serving:enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbjy = zzmg.zza(1, "gads:ad_manager_enforce_arp_invariant:enabled", (Boolean) false);
    public static final zzmg<Long> zzbjz = zzmg.zza(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
    public static final zzmg<Boolean> zzbka = zzmg.zza(1, "gads:interstitial_ad_immersive_mode", (Boolean) true);
    public static final zzmg<Boolean> zzbkb = zzmg.zza(1, "gads:custom_close_blocking:enabled", (Boolean) false);
    private static zzmg<Boolean> zzbkc = zzmg.zza(1, "gads:impression_optimization_enabled", (Boolean) false);
    private static zzmg<String> zzbkd = zzmg.zza(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static zzmg<Integer> zzbke = zzmg.zza(1, "gads:banner_ad_pool:max_queues", 3);
    private static zzmg<Integer> zzbkf = zzmg.zza(1, "gads:banner_ad_pool:max_pools", 3);
    public static final zzmg<Boolean> zzbkg = zzmg.zza(1, "gads:interstitial_ad_pool:enabled", (Boolean) false);
    public static final zzmg<Boolean> zzbkh = zzmg.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", (Boolean) false);
    public static final zzmg<String> zzbki = zzmg.zza(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final zzmg<String> zzbkj = zzmg.zza(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final zzmg<Integer> zzbkk = zzmg.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final zzmg<Integer> zzbkl = zzmg.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final zzmg<Integer> zzbkm = zzmg.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final zzmg<String> zzbkn = zzmg.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final zzmg<Integer> zzbko = zzmg.zza(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final zzmg<Integer> zzbkp = zzmg.zza(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final zzmg<Long> zzbkq = zzmg.zza(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
    public static final zzmg<Long> zzbkr = zzmg.zza(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
    public static final zzmg<Float> zzbks = zzmg.zza(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    public static final zzmg<Float> zzbkt = zzmg.zza(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    private static zzmg<Integer> zzbku = zzmg.zza(1, "gads:heap_wastage:bytes", 0);
    public static final zzmg<String> zzbkv = zzmg.zza(1, "gads:spherical_video:vertex_shader", "");
    public static final zzmg<String> zzbkw = zzmg.zza(1, "gads:spherical_video:fragment_shader", "");
    public static final zzmg<Boolean> zzbkx = zzmg.zza(0, "gads:log:verbose_enabled", (Boolean) false);
    public static final zzmg<Boolean> zzbky = zzmg.zza(1, "gads:include_local_global_rectangles", (Boolean) false);
    public static final zzmg<Long> zzbkz = zzmg.zza(1, "gads:position_watcher:throttle_ms", 200);
    public static final zzmg<Boolean> zzbla = zzmg.zza(1, "gads:include_lock_screen_apps_for_visibility", (Boolean) true);
    public static final zzmg<Boolean> zzblb = zzmg.zza(0, "gads:device_info_caching:enabled", (Boolean) true);
    public static final zzmg<Long> zzblc = zzmg.zza(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
    public static final zzmg<Boolean> zzbld = zzmg.zza(0, "gads:gen204_signals:enabled", (Boolean) false);
    public static final zzmg<Boolean> zzble = zzmg.zza(0, "gads:webview:error_reporting_enabled", (Boolean) false);
    private static zzmg<Boolean> zzblf = zzmg.zza(0, "gads:adid_reporting:enabled", (Boolean) false);
    private static zzmg<Boolean> zzblg = zzmg.zza(0, "gads:ad_settings_page_reporting:enabled", (Boolean) false);
    private static zzmg<Boolean> zzblh = zzmg.zza(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", (Boolean) false);
    private static zzmg<Boolean> zzbli = zzmg.zza(0, "gads:request_pkg:enabled", (Boolean) true);
    public static final zzmg<Boolean> zzblj = zzmg.zza(1, "gads:gmsg:disable_back_button:enabled", (Boolean) true);
    public static final zzmg<Boolean> zzblk = zzmg.zza(0, "gads:gmsg:video_meta:enabled", (Boolean) true);
    private static zzmg<String> zzbll = zzmg.zza(0, "gads:gmsg:video_meta:experiment_id");
    private static zzmg<Long> zzblm = zzmg.zza(1, "gads:network:cache_prediction_duration_s", 300);
    public static final zzmg<Long> zzbln = zzmg.zza(1, "gads:network:network_prediction_timeout_ms", 2000);
    public static final zzmg<Boolean> zzblo = zzmg.zza(0, "gads:mediation:dynamite_first:admobadapter", (Boolean) true);
    public static final zzmg<Boolean> zzblp = zzmg.zza(0, "gads:mediation:dynamite_first:adurladapter", (Boolean) true);
    public static final zzmg<Boolean> zzblq = zzmg.zza(1, "gads:bypass_adrequest_service_for_inlined_mediation", (Boolean) true);
    public static final zzmg<Long> zzblr = zzmg.zza(0, "gads:resolve_future:default_timeout_ms", 30000);
    public static final zzmg<Long> zzbls = zzmg.zza(0, "gads:ad_loader:timeout_ms", 60000);
    public static final zzmg<Long> zzblt = zzmg.zza(0, "gads:rendering:timeout_ms", 60000);
    public static final zzmg<Boolean> zzblu = zzmg.zza(0, "gads:adshield:enable_adshield_instrumentation", (Boolean) false);
    public static final zzmg<Long> zzblv = zzmg.zza(1, "gads:gestures:task_timeout", 2000);
    public static final zzmg<Boolean> zzblw = zzmg.zza(1, "gads:gestures:btt:enabled", (Boolean) false);
    public static final zzmg<Boolean> zzblx = zzmg.zza(1, "gads:gestures:sss:enabled", (Boolean) false);
    public static final zzmg<Integer> zzbly = zzmg.zza(1, "gads:gestures:ts", 1);
    public static final zzmg<Boolean> zzblz = zzmg.zza(1, "gads:gestures:tdvs:enabled", (Boolean) false);
    public static final zzmg<Boolean> zzbma = zzmg.zza(1, "gads:gestures:tvvs:enabled", (Boolean) false);
    public static final zzmg<String> zzbmb = zzmg.zza(1, "gads:gestures:pk", "");
    public static final zzmg<Boolean> zzbmc = zzmg.zza(1, "gads:gestures:bs:enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbmd = zzmg.zza(1, "gads:gestures:check_initialization_thread:enabled", (Boolean) false);
    public static final zzmg<Boolean> zzbme = zzmg.zza(1, "gads:gestures:get_query_in_non_ui_thread:enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbmf = zzmg.zza(0, "gass:enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbmg = zzmg.zza(0, "gass:enable_int_signal", (Boolean) true);
    public static final zzmg<Boolean> zzbmh = zzmg.zza(0, "gass:enable_ad_attestation_signal", (Boolean) true);
    private static zzmg<Boolean> zzbmi = zzmg.zza(0, "gads:adid_notification:first_party_check:enabled", (Boolean) true);
    private static zzmg<Boolean> zzbmj = zzmg.zza(0, "gads:edu_device_helper:enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbmk = zzmg.zza(0, "gads:support_screen_shot", (Boolean) true);
    public static final zzmg<Boolean> zzbml = zzmg.zza(0, "gads:use_get_drawing_cache_for_screenshot:enabled", (Boolean) true);
    private static zzmg<String> zzbmm = zzmg.zza(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    private static zzmg<String> zzbmn = zzmg.zza(1, "gads:sdk_core_constants:experiment_id");
    public static final zzmg<String> zzbmo = zzmg.zza(1, "gads:sdk_core_constants:caps", "");
    public static final zzmg<Long> zzbmp = zzmg.zza(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final zzmg<Boolean> zzbmq = zzmg.zza(0, "gads:js_flags:mf", (Boolean) false);
    public static final zzmg<Boolean> zzbmr = zzmg.zza(0, "gads:custom_render:ping_on_ad_rendered", (Boolean) false);
    private static zzmg<String> zzbms = zzmg.zza(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final zzmg<String> zzbmt = zzmg.zza(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    private static zzmg<String> zzbmu = zzmg.zza(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzmg<String> zzbmv = zzmg.zza(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    private static zzmg<String> zzbmw = zzmg.zza(1, "gads:singleton_webview_native:experiment_id");
    public static final zzmg<Boolean> zzbmx = zzmg.zza(1, "gads:enable_untrack_view_native", (Boolean) true);
    public static final zzmg<Boolean> zzbmy = zzmg.zza(1, "gads:ignore_untrack_view_google_native", (Boolean) true);
    public static final zzmg<Boolean> zzbmz = zzmg.zza(1, "gads:reset_listeners_preparead_native", (Boolean) true);
    public static final zzmg<Integer> zzbna = zzmg.zza(1, "gads:native_video_load_timeout", 10);
    public static final zzmg<String> zzbnb = zzmg.zza(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final zzmg<Boolean> zzbnc = zzmg.zza(1, "gads:clamp_native_video_player_dimensions", (Boolean) true);
    public static final zzmg<Boolean> zzbnd = zzmg.zza(1, "gads:enable_store_active_view_state", (Boolean) false);
    public static final zzmg<Boolean> zzbne = zzmg.zza(1, "gads:native:overlay_new_fix:enabled", (Boolean) false);
    public static final zzmg<Boolean> zzbnf = zzmg.zza(1, "gads:fluid_ad:use_wrap_content_height", (Boolean) false);
    public static final zzmg<Boolean> zzbng = zzmg.zza(0, "gads:method_tracing:enabled", (Boolean) false);
    public static final zzmg<Long> zzbnh = zzmg.zza(0, "gads:method_tracing:duration_ms", 30000);
    public static final zzmg<Integer> zzbni = zzmg.zza(0, "gads:method_tracing:count", 5);
    public static final zzmg<Integer> zzbnj = zzmg.zza(0, "gads:method_tracing:filesize", 134217728);
    private static zzmg<Boolean> zzbnk = zzmg.zza(1, "gads:auto_location_for_coarse_permission", (Boolean) false);
    private static zzmg<String> zzbnl = zzmg.zzb(1, "gads:auto_location_for_coarse_permission:experiment_id");
    public static final zzmg<Long> zzbnm = zzmg.zza(1, "gads:auto_location_timeout", 2000);
    private static zzmg<String> zzbnn = zzmg.zzb(1, "gads:auto_location_timeout:experiment_id");
    private static zzmg<Long> zzbno = zzmg.zza(1, "gads:auto_location_interval", -1);
    private static zzmg<String> zzbnp = zzmg.zzb(1, "gads:auto_location_interval:experiment_id");
    public static final zzmg<Boolean> zzbnq = zzmg.zza(1, "gads:fetch_app_settings_using_cld:enabled", (Boolean) false);
    private static zzmg<String> zzbnr = zzmg.zza(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    public static final zzmg<Long> zzbns = zzmg.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    private static zzmg<String> zzbnt = zzmg.zza(0, "gads:afs:csa:experiment_id");
    public static final zzmg<String> zzbnu = zzmg.zza(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final zzmg<String> zzbnv = zzmg.zza(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final zzmg<String> zzbnw = zzmg.zza(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final zzmg<String> zzbnx = zzmg.zza(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final zzmg<String> zzbny = zzmg.zza(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final zzmg<Long> zzbnz = zzmg.zza(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
    private static zzmg<Boolean> zzboa = zzmg.zza(0, "gads:afs:csa_ad_manager_enabled", (Boolean) true);
    private static zzmg<Boolean> zzbob = zzmg.zza(1, "gads:parental_controls:send_from_client", (Boolean) true);
    private static zzmg<Boolean> zzboc = zzmg.zza(1, "gads:parental_controls:cache_results", (Boolean) true);
    public static final zzmg<Long> zzbod = zzmg.zza(1, "gads:parental_controls:timeout", 2000);
    private static zzmg<String> zzboe = zzmg.zza(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    private static zzmg<Long> zzbof = zzmg.zza(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
    public static final zzmg<Boolean> zzbog = zzmg.zza(0, "gads:safe_browsing:debug", (Boolean) false);
    public static final zzmg<Boolean> zzboh = zzmg.zza(0, "gads:webview_cookie:enabled", (Boolean) true);
    private static zzmg<Integer> zzboi = zzmg.zza(1, "gads:cache:ad_request_timeout_millis", 250);
    private static zzmg<Integer> zzboj = zzmg.zza(1, "gads:cache:max_concurrent_downloads", 10);
    private static zzmg<Long> zzbok = zzmg.zza(1, "gads:cache:javascript_timeout_millis", 5000);
    public static final zzmg<Boolean> zzbol = zzmg.zza(1, "gads:cache:bind_on_foreground", (Boolean) false);
    public static final zzmg<Boolean> zzbom = zzmg.zza(1, "gads:cache:bind_on_init", (Boolean) false);
    public static final zzmg<Boolean> zzbon = zzmg.zza(1, "gads:cache:bind_on_request", (Boolean) false);
    public static final zzmg<Long> zzboo = zzmg.zza(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final zzmg<Boolean> zzbop = zzmg.zza(1, "gads:cache:use_cache_data_source", (Boolean) false);
    private static zzmg<Boolean> zzboq = zzmg.zza(1, "gads:cache:connection_per_read", (Boolean) false);
    private static zzmg<Long> zzbor = zzmg.zza(1, "gads:cache:connection_timeout", 5000);
    private static zzmg<Long> zzbos = zzmg.zza(1, "gads:cache:read_only_connection_timeout", 5000);
    public static final zzmg<Boolean> zzbot = zzmg.zza(1, "gads:http_assets_cache:enabled", (Boolean) false);
    public static final zzmg<String> zzbou = zzmg.zza(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final zzmg<Integer> zzbov = zzmg.zza(1, "gads:http_assets_cache:time_out", 100);
    public static final zzmg<Boolean> zzbow = zzmg.zza(1, "gads:chrome_custom_tabs:enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbox = zzmg.zza(1, "gads:chrome_custom_tabs_browser:enabled", (Boolean) false);
    public static final zzmg<Boolean> zzboy = zzmg.zza(1, "gads:chrome_custom_tabs:disabled", (Boolean) false);
    public static final zzmg<Boolean> zzboz = zzmg.zza(1, "gads:drx_in_app_preview:enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbpa = zzmg.zza(1, "gads:drx_debug_signals:enabled", (Boolean) true);
    public static final zzmg<String> zzbpb = zzmg.zza(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final zzmg<String> zzbpc = zzmg.zza(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final zzmg<String> zzbpd = zzmg.zza(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final zzmg<String> zzbpe = zzmg.zza(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final zzmg<Integer> zzbpf = zzmg.zza(1, "gads:drx_debug:timeout_ms", (int) TrueColorsPresenter.DEFAULT_LEVEL_DURATION);
    public static final zzmg<Integer> zzbpg = zzmg.zza(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final zzmg<Boolean> zzbph = zzmg.zza(1, "gad:interstitial_for_multi_window", (Boolean) false);
    public static final zzmg<Boolean> zzbpi = zzmg.zza(1, "gad:interstitial_ad_stay_active_in_multi_window", (Boolean) false);
    public static final zzmg<Integer> zzbpj = zzmg.zza(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final zzmg<Boolean> zzbpk = zzmg.zza(1, "gads:clearcut_logging:enabled", (Boolean) false);
    public static final zzmg<Boolean> zzbpl = zzmg.zza(0, "gad:force_local_ad_request_service:enabled", (Boolean) false);
    public static final zzmg<Integer> zzbpm = zzmg.zza(1, "gad:http_redirect_max_count:times", 8);
    private static zzmg<Boolean> zzbpn = zzmg.zza(0, "gads:nonagon:red_button", (Boolean) false);
    private static zzmg<Boolean> zzbpo = zzmg.zza(1, "gads:nonagon:banner:enabled", (Boolean) false);
    private static zzmg<String> zzbpp = zzmg.zza(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    private static zzmg<Boolean> zzbpq = zzmg.zza(1, "gads:nonagon:interstitial:enabled", (Boolean) false);
    private static zzmg<String> zzbpr = zzmg.zza(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    private static zzmg<Boolean> zzbps = zzmg.zza(1, "gads:nonagon:rewardedvideo:enabled", (Boolean) false);
    private static zzmg<Boolean> zzbpt = zzmg.zza(1, "gads:nonagon:mobile_ads_setting_manager:enabled", (Boolean) false);
    private static zzmg<String> zzbpu = zzmg.zza(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    private static zzmg<Boolean> zzbpv = zzmg.zza(1, "gads:nonagon:nativead:enabled", (Boolean) false);
    private static zzmg<String> zzbpw = zzmg.zza(1, "gads:nonagon:nativead:ad_unit_exclusions", "(?!)");
    private static zzmg<Boolean> zzbpx = zzmg.zza(1, "gads:nonagon:service:enabled", (Boolean) false);
    public static final zzmg<Long> zzbpy = zzmg.zza(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
    public static final zzmg<String> zzbpz = zzmg.zza(0, "gads:public_beta:traffic_multiplier", BuildConfig.VERSION_NAME);
    public static final zzmg<Boolean> zzbqa = zzmg.zza(1, "gads:real_test_request:enabled", (Boolean) true);
    public static final zzmg<Boolean> zzbqb = zzmg.zza(1, "gads:real_test_request:render_webview_label", (Boolean) true);
    public static final zzmg<Boolean> zzbqc = zzmg.zza(1, "gads:real_test_request:render_native_label", (Boolean) true);
    private static byte[] zzbqd;

    public static void initialize(Context context) {
        zzain.zza(context, new zzmr(context));
        int intValue = ((Integer) zzbs.zzep().zzd(zzbku)).intValue();
        if (intValue > 0 && zzbqd == null) {
            zzbqd = new byte[intValue];
        }
    }

    public static void zza(Context context, int i, JSONObject jSONObject) {
        zzbs.zzen();
        SharedPreferences.Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        zzbs.zzeo().zza(edit, 1, jSONObject);
        zzbs.zzen();
        edit.commit();
    }

    public static List<String> zziq() {
        return zzbs.zzeo().zziq();
    }

    public static List<String> zzir() {
        return zzbs.zzeo().zzir();
    }
}
